// <auto-generated />
using Cruise;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Cruise.Migrations
{
    [DbContext(typeof(CruiseContext))]
    [Migration("20181209051504_cruisebooking")]
    partial class cruisebooking
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cruise.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BookingDate");

                    b.Property<double>("Price");

                    b.Property<int>("ShipId");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Cruise.Models.SalesUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("Currency");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SalesUnits");
                });

            modelBuilder.Entity("Cruise.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("SalesUnitId");

                    b.HasKey("Id");

                    b.HasIndex("SalesUnitId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("Cruise.Models.Booking", b =>
                {
                    b.HasOne("Cruise.Models.Ship", "Ship")
                        .WithMany()
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cruise.Models.Ship", b =>
                {
                    b.HasOne("Cruise.Models.SalesUnit", "SalesUnit")
                        .WithMany()
                        .HasForeignKey("SalesUnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
